version: '3.3'

services:
    web:
        build: 
            dockerfile: Dockerfile
            context: .
        image: webassembly:latest
        container_name: webassembly
        
        volumes:
            - ./:/home/transfer
        
        network_mode: "host"

        restart: always